### ISSUE TITLE
Automated CSB update 

### ISSUE THREAD

**Issue by walker** [slu-openGIS/STL_CSB_RawRequests#2]
The City of St. Louis now ships the CSB requests every weekend from the ticketing application to the open data portal. The naming and location should no longer change. It's all in one zip file organized by 1 year per CSV.

https://www.stlouis-mo.gov/data/upload/data-files/csb.zip

Anything else noticed as an issue?

**Comment by chris-prener** [comment]
we discovered this recently @walker - I'm very glad to see this change and we're actually going to discontinue maintaining this repo as long as the naming/location remain consistent from here on out

**Comment by walker** [comment]
Great. It should remain consistent, barring any shakeup in staffing, technology, or directives.
